apiVersion: v1
kind: Service
metadata:
  name: springbootk8sdemo
spec:
  selector:
    app: springbootk8sdemo
  ports:
    - protocol: TCP
      port: 8090
      nodePort: 30084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootk8sdemo
spec:
  selector:
    matchLabels:
      app: springbootk8sdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootk8sdemo
    spec:
      containers:
        - name: springbootk8sdemo
          image: springbootk8sdemo
          imagePullPolicy: Never
          ports:
            - containerPort: 8090